FROM liquibase/liquibase
ADD liquibase-k8s-app/src/main/resources/db/db.changelog-dev.sql /liquibase/changelog/
CMD ["sh", "-c", "docker-entrypoint.sh --url=${DB_URL} --username=${DB_USERNAME} --password=${DB_PASSWORD} --classpath=/liquibase/changelog --changelog-file=db.changelog-${ENV}.sql update"]
