apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: liquibase-demo
type: Opaque
data:
  DB_HOST: cG9zdGdyZXMtc2VydmljZQ==   # base64("postgres-service")
  DB_NAME: ZGVtb19kYg==           # base64("demo_db")
  DB_USER: ZGVtb191c2Vy         # base64("demo_user")
  DB_PASS: ZGVtb19wYXNzd29yZA== # base64("demo_password")
