apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: liquibase-demo
type: Opaque
data:
  host: cG9zdGdyZXMtc2VydmljZQ==   # base64("postgres-service")
  dbname: ZGVtb19kYg==           # base64("demo_db")
  username: ZGVtb191c2Vy         # base64("demo_user")
  password: ZGVtb19wYXNzd29yZA== # base64("demo_password")
