apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-init-job
  namespace: liquibase-demo
spec:
  template:
    spec:
      restartPolicy: Never

      # Init container: clones your repo
      initContainers:
      - name: clone-liquibase-scripts
        image: alpine/git:latest
        command: ["/bin/sh"]
        args:
          - "-c"
          - |
            git clone https://github.com/AdityaOnCloud14/eks-liquibase-demo.git /liquibase-changelogs
        volumeMounts:
          - name: changelog-volume
            mountPath: /liquibase-changelogs

      # Main container: runs Liquibase
      containers:
      - name: liquibase
        image: liquibase/liquibase:latest
        env:
          - name: LIQUIBASE_DB_HOST
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: host
          - name: LIQUIBASE_DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: dbname
          - name: LIQUIBASE_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: LIQUIBASE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
        command: ["/bin/sh"]
        args:
          - "-c"
          - |
            JDBC_URL="jdbc:postgresql://${LIQUIBASE_DB_HOST}:5432/${LIQUIBASE_DB_NAME}"
            echo "Running Liquibase update against $JDBC_URL"

            # Move into the liquibase/ directory where the .sql and .xml files reside
            cd /liquibase-changelogs/liquibase

            # Run Liquibase referencing the master XML
            liquibase \
              --url="$JDBC_URL" \
              --username="$LIQUIBASE_DB_USERNAME" \
              --password="$LIQUIBASE_DB_PASSWORD" \
              --changeLogFile=db.changelog-master.xml \
              update
        volumeMounts:
          - name: changelog-volume
            mountPath: /liquibase-changelogs

      volumes:
      - name: changelog-volume
        emptyDir: {}
