apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-job
  namespace: liquibase-demo
spec:
  template:
    spec:
      restartPolicy: Never
      # Init container: Clone the Liquibase repository
      initContainers:
      - name: clone-liquibase-scripts
        image: alpine/git:latest
        command: ["/bin/sh"]
        args:
          - "-c"
          - |
            git clone -b feature/new --single-branch https://github.com/AdityaOnCloud14/eks-liquibase-demo.git /liquibase-changelogs
        volumeMounts:
          - name: changelog-volume
            mountPath: /liquibase-changelogs
      # Main container: Run the Liquibase command
      containers:
      - name: liquibase
        image: liquibase/liquibase:latest
        env:
          - name: LIQUIBASE_DB_HOST
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: host
          - name: LIQUIBASE_DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: dbname
          - name: LIQUIBASE_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: LIQUIBASE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
        command: ["/bin/sh"]
        args:
          - "-c"
          - |
            JDBC_URL="jdbc:postgresql://${LIQUIBASE_DB_HOST}:5432/${LIQUIBASE_DB_NAME}"
            echo "Running Liquibase command against $JDBC_URL"
            cd /liquibase-changelogs/liquibase
            liquibase --url="$JDBC_URL" --username="$LIQUIBASE_DB_USERNAME" --password="$LIQUIBASE_DB_PASSWORD" --changeLogFile=db.changelog-master.xml __LIQUIBASE_COMMAND__
        volumeMounts:
          - name: changelog-volume
            mountPath: /liquibase-changelogs
      volumes:
      - name: changelog-volume
        emptyDir: {}
