apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-job
  namespace: liquibase-demo
  labels:
    app: liquibase-migrator
spec:
  backoffLimit: 5
  template:
    metadata:
      labels:
        app: liquibase
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: changelog-volume
          emptyDir: {}
      initContainers:
        - name: git-clone
          image: alpine/git:latest
          imagePullPolicy: IfNotPresent
          args:
            - clone
            - --depth=1
            - --single-branch
            - -b
            - feature/newpipeline
            - "https://github.com/AdityaOnCloud14/eks-liquibase-demo.git"
            - "/workspace"
          volumeMounts:
            - name: changelog-volume
              mountPath: /workspace
      containers:
        - name: liquibase
          image: liquibase/liquibase:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: "__DB_HOST__"
            - name: DB_NAME
              value: "__DB_NAME__"
            - name: DB_USER
              value: "__DB_USER__"
            - name: DB_PASS
              value: "__DB_PASS__"
          volumeMounts:
            - name: changelog-volume
              mountPath: /workspace
          workingDir: /workspace/liquibase
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              JDBC_URL="jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}"
              echo "Running Liquibase command against ${JDBC_URL}"
              liquibase --url="$JDBC_URL" --username="$DB_USER" --password="$DB_PASS" --changeLogFile=db.changelog-master.xml __LIQUIBASE_COMMAND__
