apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-job
  namespace: liquibase-demo
  labels:
    app: liquibase-migrator
spec:
  backoffLimit: 0              # Fail fast if the job fails; no retries
  ttlSecondsAfterFinished: 300 # Auto-cleanup job and pods 5 minutes after completion
  template:
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: changelog-volume
          emptyDir: {}         # Ephemeral volume to share files between containers
      initContainers:
        - name: git-clone
          image: alpine/git:latest
          imagePullPolicy: IfNotPresent
          args:
            - clone
            - --depth=1
            - --single-branch
            - "https://github.com/AdityaOnCloud14/eks-liquibase-demo.git"
            - "/workspace"
          volumeMounts:
            - name: changelog-volume
              mountPath: /workspace
      containers:
        - name: liquibase
          image: liquibase/liquibase:latest
          imagePullPolicy: IfNotPresent
          # Explicit environment variable mapping from the secret
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: postgres-service
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: demo_db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: demo_user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: demo_password
          volumeMounts:
            - name: changelog-volume
              mountPath: /workspace
          workingDir: /workspace
          command: ["liquibase"]
          args:
            - "--url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}"
            - "--username=${DB_USER}"
            - "--password=${DB_PASS}"
            - "--changeLogFile=db.changelog-master.xml"
            - "__LIQUIBASE_COMMAND__"
