# harness.io/skip-file-for-deploy   <- Instruct Harness to skip this manifest in the main deployment&#8203;:contentReference[oaicite:6]{index=6}
apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-__GIT_BRANCH__                   # Job name includes branch (will be lowercased on replace)
spec:
  backoffLimit: 0                                 # Do not retry failed job (fail fast on error)
  template:
    spec:
      containers:
        - name: liquibase
          image: liquibase/liquibase:latest        # Use official Liquibase Docker image (includes PostgreSQL driver)&#8203;:contentReference[oaicite:7]{index=7}
          env:
            - name: LIQUIBASE_COMMAND_URL
              value: jdbc:postgresql://__DB_HOST__:5432/__TARGET_DB__
            - name: LIQUIBASE_COMMAND_USERNAME
              value: __DB_USER__
            - name: LIQUIBASE_COMMAND_PASSWORD
              value: __DB_PASSWORD__
            - name: LIQUIBASE_COMMAND_CHANGELOG_FILE
              value: /liquibase/changelog/master.xml   # Path to changelog file (adjust to your changelog)
          command:
            - liquibase
          args:
            - "__LIQUIBASE_COMMAND__"              # Placeholder for 'update' or 'rollbackCount X'
          # Alternatively, you could use a combined command line:
          # args:
          #   - update
          #   - --changeLogFile=/liquibase/changelog/master.xml 
          #   - --url=jdbc:postgresql://__DB_HOST__:5432/__TARGET_DB__ 
          #   - --username=__DB_USER__ 
          #   - --password=${LIQUIBASE_COMMAND_PASSWORD}
      restartPolicy: Never
