pipeline:
  name: liquibase-configmap-pipeline
  identifier: liquibase_configmap_pipeline
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: dev
        identifier: dev
        type: Deployment
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: Abort
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: liquibase_service_1
          environment:
            environmentRef: dev
            infrastructureDefinitions:
              - identifier: eks_dev_connector
          execution:
            steps:
              - step:
                  name: SQL Lint Check
                  identifier: SqlLintCheck_Dev
                  type: ShellScript
                  timeout: 2m
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          pip install sqlfluff
                          sqlfluff lint src/main/resources/db/db.changelog-dev.sql --config .sqlfluff
              - step:
                  name: Create ConfigMap
                  identifier: CreateConfigMap_Dev
                  type: ShellScript
                  timeout: 1m
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          kubectl create configmap liquibase-changelog-dev --from-file=src/main/resources/db/db.changelog-dev.sql -n liquibase-test --dry-run=client -o yaml | kubectl apply -f -
              - step:
                  name: Deploy Liquibase Update
                  identifier: DeployLiquibaseUpdate_Dev
                  type: K8sApply
                  timeout: 10m
                  spec:
                    filePaths:
                      - deploy/liquibase-update-deployment.yaml
    - stage:
        name: Rollback Dev
        identifier: Rollback_Dev
        type: Deployment
        when:
          pipelineStatus: Success
          condition: <+manual>
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: Abort
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: liquibase_service_2
          environment:
            environmentRef: dev
            infrastructureDefinitions:
              - identifier: eks_dev_connector
          execution:
            steps:
              - step:
                  name: Deploy Liquibase Rollback
                  identifier: DeployLiquibaseRollback_Dev
                  type: K8sApply
                  timeout: 10m
                  spec:
                    filePaths:
                      - deploy/liquibase-rollback-deployment.yaml
    - stage:
        name: uat
        identifier: uat
        type: Deployment
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: Abort
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: liquibase_service_1
          environment:
            environmentRef: uat
            infrastructureDefinitions:
              - identifier: eks_uat_connector
          execution:
            steps:
              - step:
                  name: SQL Lint Check
                  identifier: SqlLintCheck_UAT
                  type: ShellScript
                  timeout: 2m
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          pip install sqlfluff
                          sqlfluff lint src/main/resources/db/db.changelog-uat.sql --config .sqlfluff
              - step:
                  name: Create ConfigMap
                  identifier: CreateConfigMap_UAT
                  type: ShellScript
                  timeout: 1m
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          kubectl create configmap liquibase-changelog-uat --from-file=src/main/resources/db/db.changelog-uat.sql -n liquibase-test --dry-run=client -o yaml | kubectl apply -f -
              - step:
                  name: Deploy Liquibase Update
                  identifier: DeployLiquibaseUpdate_UAT
                  type: K8sApply
                  timeout: 10m
                  spec:
                    filePaths:
                      - deploy/liquibase-update-deployment.yaml
    - stage:
        name: Rollback UAT
        identifier: Rollback_UAT
        type: Deployment
        when:
          pipelineStatus: Success
          condition: <+manual>
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: Abort
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: liquibase_service_2
          environment:
            environmentRef: uat
            infrastructureDefinitions:
              - identifier: eks_uat_connector
          execution:
            steps:
              - step:
                  name: Deploy Liquibase Rollback
                  identifier: DeployLiquibaseRollback_UAT
                  type: K8sApply
                  timeout: 10m
                  spec:
                    filePaths:
                      - deploy/liquibase-rollback-deployment.yaml
    - stage:
        name: prod
        identifier: prod
        type: Deployment
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: Abort
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: liquibase_service_1
          environment:
            environmentRef: prod
            infrastructureDefinitions:
              - identifier: eks_prod_connector
          execution:
            steps:
              - step:
                  name: SQL Lint Check
                  identifier: SqlLintCheck_Prod
                  type: ShellScript
                  timeout: 2m
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          pip install sqlfluff
                          sqlfluff lint src/main/resources/db/db.changelog-prod.sql --config .sqlfluff
              - step:
                  name: Create ConfigMap
                  identifier: CreateConfigMap_Prod
                  type: ShellScript
                  timeout: 1m
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          kubectl create configmap liquibase-changelog-prod --from-file=src/main/resources/db/db.changelog-prod.sql -n liquibase-test --dry-run=client -o yaml | kubectl apply -f -
              - step:
                  name: Deploy Liquibase Update
                  identifier: DeployLiquibaseUpdate_Prod
                  type: K8sApply
                  timeout: 10m
                  spec:
                    filePaths:
                      - deploy/liquibase-update-deployment.yaml
    - stage:
        name: Rollback Prod
        identifier: Rollback_Prod
        type: Deployment
        when:
          pipelineStatus: Success
          condition: <+manual>
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: Abort
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: liquibase_service_2
          environment:
            environmentRef: prod
            infrastructureDefinitions:
              - identifier: eks_prod_connector
          execution:
            steps:
              - step:
                  name: Deploy Liquibase Rollback
                  identifier: DeployLiquibaseRollback_Prod
                  type: K8sApply
                  timeout: 10m
                  spec:
                    filePaths:
                      - deploy/liquibase-rollback-deployment.yaml
