name: Liquibase Pipeline

on:
  workflow_dispatch:
    inputs:
      operation:
        description: "Liquibase operation to perform (update, rollbackCount 1, or custom)"
        required: true
        default: "update"
        type: choice
        options:
          - update
          - "rollbackCount 1"
          - custom
      custom_command:
        description: 'Custom Liquibase command to run (used if operation is "custom")'
        required: false
        default: ""

jobs:
  run-liquibase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Liquibase Job manifest
        shell: bash
        run: |
          set -e
          OP="${{ inputs.operation }}"
          if [ "$OP" = "update" ]; then
            CMD="update"
          elif [ "$OP" = "rollbackCount 1" ]; then
            CMD="rollbackCount 1"
          elif [ "$OP" = "custom" ]; then
            CMD="${{ inputs.custom_command }}"
          else
            CMD="$OP"
          fi

          # Replace placeholder in the job template with the actual Liquibase command
          sed -e "s#__LIQUIBASE_COMMAND__#${CMD}#g" liquibase-job-template.yaml > liquibase-job.yaml

      - name: Apply Liquibase Job
        run: kubectl apply -f liquibase-job.yaml

      - name: Wait for Liquibase Job completion
        run: kubectl wait --for=condition=complete job/liquibase-job --timeout=300s

      - name: Fetch Liquibase Job logs
        run: kubectl logs job/liquibase-job
